### ISSUE TITLE
Add puzzle mini game daily cipher

### ISSUE THREAD

**Issue by ozzyclosy** [NabiKAZ/HamsterKombat-API#5]
Is it possible to add info about daily puzzle mini-game cipher?

Claiming puzzle mini game key seems like API call:
POST https//:api.hamsterkombat.io/clicker/claim-daily-keys-minigame
//examle for cipher 20.07.2024
{"cipher" : "MDQzNTUzNDk5N3wzMzA1NTY1NTk="}

**Comment by ozzyclosy** [comment]
cipher is personal, so its impossible

**Comment by NabiKAZ** [comment]
I remembered about Morse cipher, maybe you didn't mean it, but I wrote it here:
https://twitter.com/NabiKAZ/status/1800811012641448322

As for the mini game, If you decode your own base64 code, you will understand.
it is enough to enter a random number and Telegram ID with `|` Combine and base64 and send as cipher. Code like this:
```javascrript
const cipher = 0 + String(randomNumber(100000000, 999999999)) + '|' + telegramId;
const cipherEncoded = Buffer.from(cipher).toString('base64');
var res = await getUrl('https://api.hamsterkombatgame.io/clicker/claim-daily-keys-minigame', account, {
    cipher: cipherEncoded,
});
```
