### ISSUE TITLE
images for hamster combo

### ISSUE THREAD

**Issue by oleks-kr** [NabiKAZ/HamsterKombat-API#8]
hi
is it possible to retrieve combo images from somewhere?

**Comment by oleks-kr** [comment]
for example the same API but for images

**Comment by NabiKAZ** [comment]
The format of the photos is as follows:
https://hamsterkombatgame.io/images/upgrade/<ID>.png
example: https://hamsterkombatgame.io/images/upgrade/fan_tokens.png
For ID, you can refer to:
https://hamsterkombatgame.io/_nuxt/mine.PLot8KdU.js
You can see them from about line 320.

Or tell chatGPT to write a simple js code that will extract all the addresses of the images on the page and start the game by this script:
https://github.com/NabiKAZ/HamsterKombat-scripts
Open under the web and run the script in the console on the web page.
